### ISSUE TITLE
Prevent block usage on inappropriate pages

### ISSUE THREAD

**Issue by abias** [netsapiensis/moodle-block_course_menu#13]
Hi,

your block_course_menu is usable on all kinds of pages. But, in my opinion, it only makes sense on course pages. Could you please add the following function to your block?

function applicable_formats() {
    return array('course' => true, 'course-category' => false);
}

If you want your block to be added as sticky block, the function would be:

function applicable_formats() {
    return array('course' => true, 'course-category' => false, 'site' => true);
}

Thanks in advance
Alex

**Comment by netsapiensis** [comment]
Hi,

The ability to place the Course Menu block on other places than course pages is by design and used by people. You can even choose to have an alternative name for the Course Menu block when it's shown outside course pages.

Regards
Alex Contis
NetSapiensis AB

**Comment by abias** [comment]
Hi Alex,

thanks for the quick reply. That sounds reasonable.

Alex
